apiVersion: v2
appVersion: v0.0.7
description: 'The ClickHouse Operator is a Kubernetes operator that automates the
  deployment, configuration, and management of ClickHouse clusters and ClickHouse
  Keeper clusters on Kubernetes. It provides declarative cluster management through
  custom resources, enabling users to easily create highly-available ClickHouse deployments. '
home: https://github.com/ClickHouse/clickhouse-operator
icon: https://clickhouse.com/docs/img/clickhouse-operator-logo.svg
keywords:
- database
- clickhouse
kubeVersion: '>= 1.28.0-0'
maintainers:
- email: operator@clickhouse.com
  name: ClickHouse Team
name: clickhouse-operator-helm
type: application
version: 0.0.7
